name: any_push
on: push
jobs:
  one:
    runs-on: ubuntu-latest
    name: something that doesnt exist
    steps:
      - name: This is the first step - HELLO WORLD
        run: | 
          echo "Hello World Tim"
